### PR TITLE
Some added CRAN polish and updates (closes #48)

### LINKED ISSUE #48: CRAN changes
In mail overnight:

> This concerns packages

> APSIM AnaCoDa BAT CCAGFA CausalFX DivMelt Dominance FCPS FHDI LMest
Mega2R MetaSKAT MissMech Momocs NSM3 PEIP PSPManalysis PhyInformR PoSI
RSSL RcppSMC Ryacas0 SCCS SMDIC SRRS SeleMix SimDesign SpatialExtremes
StatCharrms StrathE2E2 TVMM Tmisc XMRF acm4r apTreeshape bayeslm
binman bio.infer cem cgh collidr cpm crblocks crskdiag diagram edeaR
effsize eicm emuR fSRM fasstr fast fbar fsbrain gaston gensemble
gensvm ggiraphExtra gkmSVM i2dash inspectdf kmconfband labstatR linkR
linkcomm mateable mco mlegp mortAAR multitaper network nmfgpu4R
noisyCE2 openCR openair pMineR pbdNCDF4 phuse plethem plot3logit
priceR radsafer regsem resumer ribiosUtils rock ropenblas sazedR
sbpiper scidb searchable simPop simone sna snnR softmaxreg spsurvey
svgViewR tailr tclust titan tmod tsgui webglobe woeR wru xseq
zooaRchGUI ztable

> A new check in R-devel (part of --as-cran) looks for return without (): this
is reported on the CRAN results pages for fedora-clang and fedora-gcc.

> Please check the report for your package and either submit a correction before
Oct 1 or let us know that you think this is a false positive.

I can reproduce this and will prepare a quick fix, along with addressing a few other things that have cropped up. It will in a proper branch leading to a PR for all to review.

### PR DESCRIPTION
**Pull request by eddelbuettel**
The changes are split over three commits where

1. addresses the initial complaint from the email quoted in #48 
2. addresses what comes up these days in `R CMD check --as-cran`, it is all minor but happy to discuss one by one
3. just rolls the version to an intermediate minor to create a different .tar.gz

Let me know what you think, there is no _real_ need for action.

### CODE REVIEW

**Review by adamjohansen — APPROVED** [review]
Thanks for taking care of this, @eddelbuettel , it all looks good to me.

**Comment by eddelbuettel** [comment]
I'll slap a 0.2.2 label on it and ship it to CRAN to satisfy their request quoted in #48.

**Comment by LeahPrice** [comment]
Thanks Dirk! I hope you're both well. Sorry for the slow reply.

**Comment by eddelbuettel** [comment]
No worries.  Time zones and all, plus the weekend (which is simply a good time for me to do some open source work with a fresh coffee.)

Release 0.2.2 just hit CRAN.

**Pull request merged**
