### PR TITLE
use std::pow instead of pow to fix solaris build

### PR DESCRIPTION
**Pull request by eddelbuettel**
We seem to fail to build on Slowlaris as seen [here](https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/RcppSMC-00install.html).

This may help.

### CODE REVIEW

**Comment by adamjohansen** [comment]
Thanks Dirk, this looks pretty uncontroversial to me... fingers crossed that it resolves the ambiguity.

**Comment by eddelbuettel** [comment]
I tried it at r-hub in order to use solaris, but the builder had a network issue.  Log [is here](https://builder.r-hub.io/status/RcppSMC_0.2.0.3.tar.gz-18c33abf1b38437db1bee2febf8d7782).

**Comment by eddelbuettel** [comment]
Wow. @gaborcsardi already fixed the [rhub issue I filed](https://github.com/r-hub/rhub/issues/126#event-1526998257) and I just checked the package with this PR there.  No issue.  (Now, I am not fully sure that it is the identical setup but probably close enough.

**Comment by eddelbuettel** [comment]
Hah!  When I check the master branch (without the `std::pow()` change) it does indeed break.  

So PR is good.

**Comment by adamjohansen** [comment]
Excellent... any reason not to merge?

**Comment by tibi77** [comment]
Why the `pow` from `src/blockpfgaussianopt.cpp` is not changed? Is there a reason that I am missing? (Asking from a consistency point of view).

**Comment by eddelbuettel** [comment]
@adamjohansen No, I'll do it later.
@tibi77 You can comment on the actual line. Some remain because they are in `arma::pow()`; the confusion (for the Solaris compiler) arose over `std::pow()`

**Pull request merged**
